server:
  port: 80

#配置这个后，相应的Fallback或者FallbackFactory就可以正常使用降级功能
feign:
  circuitbreaker:
    enabled: true

#Eureka配置
eureka:
  client:
    register-with-eureka: false #消费者不用向Eureka注册自己，只需要找提供者拿就好了
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/


