server:
  port: 8003
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  type-aliases-package: com.demo.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept #应用的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eis2?useUnicode=true&characterEncoding-utf-8
    username: root
    password: 123456

#eureka的配置，服务注册到哪里，提供者要找到注册中心
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/ #集群情况下的提供者发布配置网址
  instance:
    instance-id: springcloud-provider-dept8003 #修改eureka上的默认描述信息

#info配置 随便写的
info:
  app.name: demo-yjn
  company.name: yangejining.springcloud.com
